
splashWords = {
  'raint',
  'awesome',
  'farkin great, mate',
  'hella dope',
  'the dopest',
  'way more doper',
  'hella bomb',
  'the dopeswt',
  'the dopest',
  'the schsit',
  'hell in a handbasket',
  'your grandmas minecraft',
  'a chore',
  'the last time',
  'your end',
  'the death of you',
  'your downfall',
  'the last thing you ever do',
  'the thing that makes you confront your mortality',
  'the best game you\'ve ever played',
  'the worst game you\'ve ever played',
  "the first line\nThis is the second one.\n(and a third)\n\nfifth",
  "escapism",
  "going to keep you up all night",
  "made by Mike Lyons",
  "!!",
  "the lastn't you'll see of me",
  "whutre ya bruddahin’ up?\n whatn’t ain’t up?\n hain’t\n rain’t",
}
-- @TODO get prettier RGB colors - maybe match them to the text table, maybe multiple colors
splashColors = {
  {255,0,0,255},
  {0,255,0,255},
  {0,0,255,255},
  {55,55,55,255},
  {55,55,55,255},
  {155,55,55,255},
  {55,155,55,255},
  {55,55,155,255},
}
