local denver = require '../../lib/denver'

local effects = {}

-- bleeping
function effects.loop1()
-- A community that feels relief from hangovers and are looking for answers as to why. Most of us are diagnosed with ADHD and exhibit depression, anxiety and fatigue but feel complete remission from all symptoms when hungover from alcohol. If you feel the same way, join us and let's find a cure.
  print('=== first loop ===')
  for i=4,1,-1 do print(i)
    print('=== '..i..' loop ===')
    local sine = denver.get({waveform='sinus', frequency=540, length=0.1})
    love.audio.play(sine)
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=040, length=0.1})
    love.audio.play(sine)
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=140, length=0.1})
    love.audio.play(sine)
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=240, length=0.1})
    love.audio.play(sine)
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=940, length=0.1})
    love.audio.play(sine)
  end
  print('=== END LOOP 1 == ')
end

-- Failure spiral
function effects.loop2()
  print('=== LOOP 2 === ')
  for i=7,1,-1 do print(i)
    print('=== LOOP 2 AGAIN === ')
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=70*i, length=0.2})
    local saw  = denver.get({waveform='sawtooth', frequency=700*i, length=0.2})
    local saw  = denver.get({waveform='sawtooth', frequency=70*i, length=0.2})
    local saw2  = denver.get({waveform='sawtooth', frequency=50*i, length=0.2})
    local saw3  = denver.get({waveform='sawtooth', frequency=30*i, length=0.2})
    love.audio.play(sine)
    love.audio.play(saw)
    love.audio.play(saw2)
    love.audio.play(saw3)
    local sine = denver.get({waveform='sinus', frequency=340, length=0.15})
    love.audio.play(sine)
    love.timer.sleep(0.1)
    local sine = denver.get({waveform='sinus', frequency=540, length=0.35})
    love.audio.play(sine)
    love.timer.sleep(0.2)
    local sine = denver.get({waveform='sinus', frequency=840, length=0.45})
    love.audio.play(sine)
    love.timer.sleep(0.3)
    local sine = denver.get({waveform='sinus', frequency=990, length=0.15})
    love.audio.play(sine)
    love.timer.sleep(0.5)
    local sine = denver.get({waveform='sinus', frequency=190, length=0.15})
    love.audio.play(sine)
    love.timer.sleep(0.3)
    local sine = denver.get({waveform='sinus', frequency=1290, length=0.05})
    love.audio.play(sine)
  end
  print('=== END LOOP 2 === ')
end

-- minor resolution
function effects.loop3()
  print('=== SOME SHIT === ')
  local sine = denver.get({waveform='sinus', frequency=740, length=0.1})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=840, length=0.1})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=840, length=0.1})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=890, length=0.1})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=340, length=0.25})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=540, length=0.25})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=840, length=0.25})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=990, length=0.25})
  love.audio.play(sine)
    love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency=190, length=0.25})
  love.audio.play(sine)
    love.timer.sleep(0.1)
end

-- waves of bullshit
function effects.loop4()
  print('=== Noise 2')
  local sine = denver.get({waveform='sinus', frequency='A', length=1.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='B', length=0.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='C', length=0.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='D', length=0.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='E', length=0.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='F', length=0.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='A', length=1.75})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='B', length=0.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='C', length=0.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='D', length=0.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='E', length=0.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
  local sine = denver.get({waveform='sinus', frequency='F', length=0.25})
  love.audio.play(sine)
  love.timer.sleep(0.1)
end

function effects.loop5()
  -- play a sinus of 1sec at 440Hz
  print('=== SINUS 1 === ')
  local sine = denver.get({waveform='sinus', frequency=440, length=0.1})
  love.audio.play(sine)

  -- play a F#2 (available os)
  --low base note
  print('=== Square 1 === ')
  local square = denver.get({waveform='square', frequency='F#2', length=0.1})
  love.audio.play(square)
end

return effects