--[[
  states/ai found note/note.lua
  This code is generated by chatGPT
  @TODO - 
  - blend it into existing gamestate management
  - get it working
  - trigger it if it works adapt it er wudever

Here is a game mode implemented in Lua with LÖVE2D that represents picking up a procedurally generated note on the sidewalk. The note and its handwriting are displayed in an immediate mode GUI. This example assumes you are transitioning from a platformer game to a modal pickup screen.

To handle this, I'll create two main states: platformer and notePickup. The notePickup state will be the modal screen that allows the player to view the procedurally generated note.
]]
local GameState = "platformer" -- Can be "platformer" or "notePickup"
local player = { x = 100, y = 300, w = 50, h = 50 } -- Simplified player
local note = { x = 400, y = 350, w = 30, h = 30, pickedUp = false }
local showNoteScreen = false
local noteText = ""
local font
local transitionAlpha = 0

function love.load()
    font = love.graphics.newFont(24)
end

function love.update(dt)
    if GameState == "platformer" then
        -- Handle platformer game logic
        platformerUpdate(dt)
    elseif GameState == "notePickup" then
        -- Handle notePickup screen logic (if any)
        transitionAlpha = math.min(transitionAlpha + dt * 2, 1)
    end
end

function love.draw()
    if GameState == "platformer" then
        platformerDraw()
    elseif GameState == "notePickup" then
        notePickupDraw()
    end
end

function platformerUpdate(dt)
    -- Simple player movement (left/right)
    if love.keyboard.isDown("left") then
        player.x = player.x - 200 * dt
    elseif love.keyboard.isDown("right") then
        player.x = player.x + 200 * dt
    end

    -- Check for note collision
    if checkCollision(player, note) and love.keyboard.isDown("space") then
        GameState = "notePickup"
        note.pickedUp = true
        noteText = generateNoteText()
        transitionAlpha = 0 -- Start the transition
    end
end

function platformerDraw()
    -- Draw platformer environment
    love.graphics.setColor(1, 1, 1)
    love.graphics.rectangle("fill", player.x, player.y, player.w, player.h)

    if not note.pickedUp then
        love.graphics.setColor(1, 1, 0)
        love.graphics.rectangle("fill", note.x, note.y, note.w, note.h)
    end
end

function notePickupDraw()
    -- Darken the background
    love.graphics.setColor(0, 0, 0, 0.5)
    love.graphics.rectangle("fill", 0, 0, love.graphics.getWidth(), love.graphics.getHeight())

    -- Draw the note
    love.graphics.setColor(1, 1, 1, transitionAlpha)
    love.graphics.rectangle("fill", 100, 100, 600, 400)

    -- Display the note text
    love.graphics.setFont(font)
    love.graphics.setColor(0, 0, 0, transitionAlpha)
    love.graphics.printf(noteText, 120, 120, 560)

    -- Show instruction to exit
    love.graphics.printf("Press 'Esc' to close the note.", 120, 450, 560, "center")
end

function love.keypressed(key)
    if GameState == "notePickup" and key == "escape" then
        GameState = "platformer"
    end
end

function checkCollision(a, b)
    return a.x < b.x + b.w and
           b.x < a.x + a.w and
           a.y < b.y + b.h and
           b.y < a.y + a.h
end

function generateNoteText()
    -- Generate random note text. You can customize this as needed.
    local notes = {
        "Meet me at the park at 7.",
        "Don't forget to buy milk!",
        "I saw what you did...",
        "The treasure is buried near the old tree.",
        "Call me when you get this."
    }
    return notes[math.random(#notes)]
end

--[[
Explanation
State Management: The GameState variable manages which part of the game is active. The platformer gameplay happens in the platformer state, and the modal note pickup screen is in the notePickup state.

Transition to Note Screen: When the player collides with the note and presses the "space" key, the game transitions from the platformer state to the notePickup state. The transition is animated using a fade-in effect controlled by transitionAlpha.

Note Generation: The generateNoteText function creates a random note from a predefined set of messages. You can expand this with more complex procedural generation.

Drawing the Note: When in the notePickup state, the screen darkens, and the note is displayed in the middle of the screen. The note text is shown with a simple instruction to close the note by pressing the "Esc" key.

Returning to the Platformer: Pressing "Esc" returns the game to the platformer state.

This is a simple yet extensible implementation. You can build upon this by adding more complexity to the note generation, including different handwriting fonts, more detailed notes, and enhanced transitions.
]]
