DEBUG_NOSPLASH = false

DEBUG_CONSOLE_FUNCTION = false

DEBUG_HITBOX_VIS = true
DEBUG_HITBOX_UI = true

DEBUG_GRID_ON = false

DEBUG_SHOW_FPS = true

--==============
--LOGGING LEVELS
--==============
DEBUG_LOGGING_ON = true
DEBUG_LOGGING_COLLISION = false
DEBUG_LOGGING_CHUNKS = false
DEBUG_PRESSSTART_OFF = true
